apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-web-application
  name: admin-web-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-web-application
  strategy: {}
  template:
    metadata:
      labels:
        app: admin-web-application
    spec:
      containers:
        - env:
            - name: RDS_DB_NAME
              value: dbprodultrapurewater
            - name: RDS_HOSTNAME
              value: mysql
            - name: RDS_PASSWORD
              value: Vosa1234.+-UltraPureWater+Adam&
            - name: RDS_PORT
              value: "3306"
            - name: RDS_USERNAME
              value: ultrapurewater
          image: docker.io/ivosahlik/adminportal:0.0.6
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8080
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
              path: /health-check
              port: 8080
            initialDelaySeconds: 45
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 1Gi
          imagePullPolicy: Always
          name: admin-web-application
          ports:
            - containerPort: 8080
      restartPolicy: Always
status: {}
