apiVersion: v1
kind: Service
metadata:
  name: admin-web-application
  labels:
    app: admin-web-application
spec:
  selector:
    app: admin-web-application
  ports:
    - name: http
      port: 8081
      targetPort: 8080
  type: LoadBalancer
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: myingress
#  labels:
#    name: myingress
#spec:
#  rules:
#    - host: ivosahlik.cz
#      http:
#        paths:
#          - pathType: Prefix
#            path: "/"
#            backend:
#              service:
#                name: admin-web-application
#                port:
#                  number: 8081
