apiVersion: v1
kind: Service
metadata:
  name: admin-membrania-web-application
  labels:
    app: admin-membrania-web-application
spec:
  selector:
    app: admin-membrania-web-application
  ports:
    - name: http
      port: 8091
      targetPort: 8080
  type: LoadBalancer
---
# HTTPS ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-admin.membrania.eu
  labels:
    name: ingress-admin.membrania.eu
  namespace: web2-cz-prod
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-admin.membrania.eu
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/preserve-host: "true"
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/redirect-regex: "^https://admin.membrania.eu/(.*)"
    traefik.ingress.kubernetes.io/redirect-replacement: "https://admin.membrania.eu/$1"
spec:
  rules:
    - host: admin.membrania.eu
      http:
        paths:
          - pathType: Prefix
            path: "/adminportal"
            backend:
              service:
                name: admin-membrania-web-application
                port:
                  number: 8091
  tls:
    - hosts:
        - admin.membrania.eu
      secretName: admin.membrania.eu.info-tls
#---
## Redirect to https
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: redirect-https
#spec:
#  redirectScheme:
#    scheme: https
#    permanent: true
---
# http ingress for http->https redirection
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-admin.membrania.eu-redirect
  namespace: web2-cz-prod
  annotations:
    # https://aqibrahman.com/set-up-traefik-kubernetes-ingress-for-http-and-https-with-redirect-to-https
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: web2-cz-prod-redirect-https@kubernetescrd
spec:
  rules:
    - host: admin.membrania.eu
      http:
        paths:
          - pathType: Prefix
            path: "/adminportal"
            backend:
              service:
                name: admin-membrania-web-application
                port:
                  number: 8091
