apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eshop-membrania-web-application
  name: eshop-membrania-web-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-membrania-web-application
  strategy: {}
  template:
    metadata:
      labels:
        app: eshop-membrania-web-application
    spec:
      containers:
        - name: eshop-membrania-web-application
          image: docker.io/ivosahlik/eshopweb:0.0.6
#          livenessProbe:
#            httpGet:
#              path: /health-check
#              port: 8084
#            initialDelaySeconds: 45
#          readinessProbe:
#            httpGet:
#              path: /health-check
#              port: 8084
#            initialDelaySeconds: 45
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 1Gi
          imagePullPolicy: Always
          env:
          - name: JAVA_TOOL_OPTIONS
            value: >-
              -Dspring.profiles.active=prod
              -Ddeployment.application=membrania
          - name: RDS_DB_NAME
            value: dbprodultrapurewater
          - name: RDS_HOSTNAME
            value: mysql
          - name: RDS_PASSWORD
            value: Vosa1234.+-UltraPureWater+Adam&
          - name: RDS_PORT
            value: "3306"
          - name: RDS_USERNAME
            value: ultrapurewater
#          - name: JAVA_TOOL_OPTIONS
#            value: >-
#              -Dspring.profiles.active=dev
#              -Ddeployment.application=membrania
#          - name: RDS_DB_NAME
#            value: dbprodultrapurewater
#          - name: RDS_HOSTNAME
#            value: mysql
#          - name: RDS_PASSWORD
#            value: dummypassword
#          - name: RDS_PORT
#            value: "3306"
#          - name: RDS_USERNAME
#            value: ultrapurewater
          ports:
            - containerPort: 8080
      restartPolicy: Always
status: {}
