apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: dbprodultrapurewater
            - name: MYSQL_PASSWORD
              value: Vosa1234.+-UltraPureWater+Adam&
            - name: MYSQL_ROOT_PASSWORD
              value: Vosa1234.+-UltraPureWater+Adam&
            - name: MYSQL_USER
              value: ultrapurewater
          image: docker.io/ivosahlik/mysql:5.7
          args:
            - "--ignore-db-dir=lost+found"
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-database-data-volume
      restartPolicy: Always
      volumes:
        - name: mysql-database-data-volume
          persistentVolumeClaim:
            claimName: mysql-database-data-volume
status: {}
