apiVersion: v1
kind: Service
metadata:
  name: eshop-membrania-web-application
  labels:
    app: eshop-membrania-web-application
spec:
  selector:
    app: eshop-membrania-web-application
  ports:
    - name: http
      port: 8088
      targetPort: 8080
  type: LoadBalancer
---
# HTTPS ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-membrania.eu
  labels:
    name: ingress-membrania.eu
#  namespace: web2-cz-prod
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/redirect-regex: ^http://.*?membrania.eu/|^https://membrania.eu/(.*)
    traefik.ingress.kubernetes.io/redirect-replacement: https://membrania.eu/$1
spec:
  rules:
    - host: membrania.eu
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: eshop-membrania-web-application
                port:
                  number: 8088
    - host: www.membrania.eu
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: eshop-membrania-web-application
                port:
                  number: 8088
  tls:
    - hosts:
        - membrania.eu
        - www.membrania.eu
      secretName: membrania.eu.ssl-secret
---
# Redirect to https
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
# http ingress for http->https redirection
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-membrania.eu-redirect
#  namespace: web2-cz-prod
  annotations:
    # https://aqibrahman.com/set-up-traefik-kubernetes-ingress-for-http-and-https-with-redirect-to-https
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: web2-cz-prod-redirect-https@kubernetescrd
spec:
  rules:
    - host: membrania.eu
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: eshop-membrania-web-application
                port:
                  number: 8088
    - host: www.membrania.eu
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: eshop-membrania-web-application
                port:
                  number: 8088
