apiVersion: v1
kind: Service
metadata:
  name: eshop-dcsolutions-web-application
  labels:
    app: eshop-dcsolutions-web-application
spec:
  selector:
    app: eshop-dcsolutions-web-application
  ports:
    - name: http
      port: 8096
      targetPort: 8080
  type: LoadBalancer
---
# HTTPS ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dcsolutions.cz
  labels:
    name: ingress-dcsolutions.cz
  namespace: web2-cz-prod
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-dcsolutions.cz
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/redirect-regex: ^http://.*?dcsolutions.cz/|^https://dcsolutions.cz/(.*)
    traefik.ingress.kubernetes.io/redirect-replacement: https://dcsolutions.cz/$1
spec:
  rules:
    - host: dcsolutions.cz
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: eshop-dcsolutions-web-application
                port:
                  number: 8096
    - host: www.dcsolutions.cz
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: eshop-dcsolutions-web-application
                port:
                  number: 8096
  tls:
    - hosts:
        - dcsolutions.cz
        - www.dcsolutions.cz
      secretName: dcsolutions.cz.info-tls
#---
## Redirect to https
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: redirect-https
#spec:
#  redirectScheme:
#    scheme: https
#    permanent: true
---
# http ingress for http->https redirection
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-dcsolutions.cz-redirect
  namespace: web2-cz-prod
  annotations:
    # https://aqibrahman.com/set-up-traefik-kubernetes-ingress-for-http-and-https-with-redirect-to-https
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: web2-cz-prod-redirect-https@kubernetescrd
spec:
  rules:
    - host: dcsolutions.cz
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: eshop-dcsolutions-web-application
                port:
                  number: 8096
    - host: www.dcsolutions.cz
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: eshop-dcsolutions-web-application
                port:
                  number: 8096
